/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-shared-Enums-Check.h.zapt

#pragma once

#include <clusters/shared/Enums.h>

namespace chip {
namespace app {
namespace Clusters {
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::ChangeIndicationEnum val)
{
    using EnumType = detail::ChangeIndicationEnum;
    switch (val)
    {
    case EnumType::kOk:
    case EnumType::kWarning:
    case EnumType::kCritical:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::CharacteristicEnum val)
{
    using EnumType = detail::CharacteristicEnum;
    switch (val)
    {
    case EnumType::kForcedSubtitles:
    case EnumType::kDescribesVideo:
    case EnumType::kEasyToRead:
    case EnumType::kFrameBased:
    case EnumType::kMainProgram:
    case EnumType::kOriginalContent:
    case EnumType::kVoiceOverTranslation:
    case EnumType::kCaption:
    case EnumType::kSubtitle:
    case EnumType::kAlternate:
    case EnumType::kSupplementary:
    case EnumType::kCommentary:
    case EnumType::kDubbedTranslation:
    case EnumType::kDescription:
    case EnumType::kMetadata:
    case EnumType::kEnhancedAudioIntelligibility:
    case EnumType::kEmergency:
    case EnumType::kKaraoke:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::DegradationDirectionEnum val)
{
    using EnumType = detail::DegradationDirectionEnum;
    switch (val)
    {
    case EnumType::kUp:
    case EnumType::kDown:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::LevelValueEnum val)
{
    using EnumType = detail::LevelValueEnum;
    switch (val)
    {
    case EnumType::kUnknown:
    case EnumType::kLow:
    case EnumType::kMedium:
    case EnumType::kHigh:
    case EnumType::kCritical:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::MeasurementMediumEnum val)
{
    using EnumType = detail::MeasurementMediumEnum;
    switch (val)
    {
    case EnumType::kAir:
    case EnumType::kWater:
    case EnumType::kSoil:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::MeasurementUnitEnum val)
{
    using EnumType = detail::MeasurementUnitEnum;
    switch (val)
    {
    case EnumType::kPpm:
    case EnumType::kPpb:
    case EnumType::kPpt:
    case EnumType::kMgm3:
    case EnumType::kUgm3:
    case EnumType::kNgm3:
    case EnumType::kPm3:
    case EnumType::kBqm3:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(detail::ProductIdentifierTypeEnum val)
{
    using EnumType = detail::ProductIdentifierTypeEnum;
    switch (val)
    {
    case EnumType::kUpc:
    case EnumType::kGtin8:
    case EnumType::kEan:
    case EnumType::kGtin14:
    case EnumType::kOem:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::AlarmSeverityTag val)
{
    using EnumType = Globals::AlarmSeverityTag;
    switch (val)
    {
    case EnumType::kCritical:
    case EnumType::kMajor:
    case EnumType::kMinor:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::AmbientAudioContextTag val)
{
    using EnumType = Globals::AmbientAudioContextTag;
    switch (val)
    {
    case EnumType::kUnknown:
    case EnumType::kObjectFall:
    case EnumType::kSnoring:
    case EnumType::kCoughing:
    case EnumType::kBarking:
    case EnumType::kShattering:
    case EnumType::kBabyCrying:
    case EnumType::kUtilityAlarm:
    case EnumType::kUrgentShouting:
    case EnumType::kDoorbell:
    case EnumType::kKnocking:
    case EnumType::kUrgentSiren:
    case EnumType::kFaucetRunning:
    case EnumType::kKettleBoiling:
    case EnumType::kFanDryer:
    case EnumType::kClapping:
    case EnumType::kFingerSnapping:
    case EnumType::kMeowing:
    case EnumType::kLaughing:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::AreaTypeTag val)
{
    using EnumType = Globals::AreaTypeTag;
    switch (val)
    {
    case EnumType::kAisle:
    case EnumType::kAttic:
    case EnumType::kBackDoor:
    case EnumType::kBackYard:
    case EnumType::kBalcony:
    case EnumType::kBallroom:
    case EnumType::kBathroom:
    case EnumType::kBedroom:
    case EnumType::kBorder:
    case EnumType::kBoxroom:
    case EnumType::kBreakfastRoom:
    case EnumType::kCarport:
    case EnumType::kCellar:
    case EnumType::kCloakroom:
    case EnumType::kCloset:
    case EnumType::kConservatory:
    case EnumType::kCorridor:
    case EnumType::kCraftRoom:
    case EnumType::kCupboard:
    case EnumType::kDeck:
    case EnumType::kDen:
    case EnumType::kDining:
    case EnumType::kDrawingRoom:
    case EnumType::kDressingRoom:
    case EnumType::kDriveway:
    case EnumType::kElevator:
    case EnumType::kEnsuite:
    case EnumType::kEntrance:
    case EnumType::kEntryway:
    case EnumType::kFamilyRoom:
    case EnumType::kFoyer:
    case EnumType::kFrontDoor:
    case EnumType::kFrontYard:
    case EnumType::kGameRoom:
    case EnumType::kGarage:
    case EnumType::kGarageDoor:
    case EnumType::kGarden:
    case EnumType::kGardenDoor:
    case EnumType::kGuestBathroom:
    case EnumType::kGuestBedroom:
    case EnumType::kGuestRoom:
    case EnumType::kGym:
    case EnumType::kHallway:
    case EnumType::kHearthRoom:
    case EnumType::kKidsRoom:
    case EnumType::kKidsBedroom:
    case EnumType::kKitchen:
    case EnumType::kLaundryRoom:
    case EnumType::kLawn:
    case EnumType::kLibrary:
    case EnumType::kLivingRoom:
    case EnumType::kLounge:
    case EnumType::kMediaTvRoom:
    case EnumType::kMudRoom:
    case EnumType::kMusicRoom:
    case EnumType::kNursery:
    case EnumType::kOffice:
    case EnumType::kOutdoorKitchen:
    case EnumType::kOutside:
    case EnumType::kPantry:
    case EnumType::kParkingLot:
    case EnumType::kParlor:
    case EnumType::kPatio:
    case EnumType::kPlayRoom:
    case EnumType::kPoolRoom:
    case EnumType::kPorch:
    case EnumType::kPrimaryBathroom:
    case EnumType::kPrimaryBedroom:
    case EnumType::kRamp:
    case EnumType::kReceptionRoom:
    case EnumType::kRecreationRoom:
    case EnumType::kRoof:
    case EnumType::kSauna:
    case EnumType::kScullery:
    case EnumType::kSewingRoom:
    case EnumType::kShed:
    case EnumType::kSideDoor:
    case EnumType::kSideYard:
    case EnumType::kSittingRoom:
    case EnumType::kSnug:
    case EnumType::kSpa:
    case EnumType::kStaircase:
    case EnumType::kSteamRoom:
    case EnumType::kStorageRoom:
    case EnumType::kStudio:
    case EnumType::kStudy:
    case EnumType::kSunRoom:
    case EnumType::kSwimmingPool:
    case EnumType::kTerrace:
    case EnumType::kUtilityRoom:
    case EnumType::kWard:
    case EnumType::kWorkshop:
    case EnumType::kToilet:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::AtomicRequestTypeEnum val)
{
    using EnumType = Globals::AtomicRequestTypeEnum;
    switch (val)
    {
    case EnumType::kBeginWrite:
    case EnumType::kCommitWrite:
    case EnumType::kRollbackWrite:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ClosureCabinetTag val)
{
    using EnumType = Globals::ClosureCabinetTag;
    switch (val)
    {
    case EnumType::kCabinetDoor:
    case EnumType::kDrawer:
    case EnumType::kFlap:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ClosureCoveringTag val)
{
    using EnumType = Globals::ClosureCoveringTag;
    switch (val)
    {
    case EnumType::kBlind:
    case EnumType::kAwning:
    case EnumType::kShutter:
    case EnumType::kVenetian:
    case EnumType::kCurtain:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ClosurePanelTag val)
{
    using EnumType = Globals::ClosurePanelTag;
    switch (val)
    {
    case EnumType::kLift:
    case EnumType::kTilt:
    case EnumType::kSliding:
    case EnumType::kRotate:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ClosureTag val)
{
    using EnumType = Globals::ClosureTag;
    switch (val)
    {
    case EnumType::kOpening:
    case EnumType::kClosing:
    case EnumType::kStop:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ClosureWindowTag val)
{
    using EnumType = Globals::ClosureWindowTag;
    switch (val)
    {
    case EnumType::kRoof:
    case EnumType::kFacade:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::CommodityTariffChronologyTag val)
{
    using EnumType = Globals::CommodityTariffChronologyTag;
    switch (val)
    {
    case EnumType::kCurrent:
    case EnumType::kPrevious:
    case EnumType::kUpcoming:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::CommodityTariffCommodityTag val)
{
    using EnumType = Globals::CommodityTariffCommodityTag;
    switch (val)
    {
    case EnumType::kElectricalEnergy:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::CommodityTariffFlowTag val)
{
    using EnumType = Globals::CommodityTariffFlowTag;
    switch (val)
    {
    case EnumType::kImport:
    case EnumType::kExport:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::CompassDirectionTag val)
{
    using EnumType = Globals::CompassDirectionTag;
    switch (val)
    {
    case EnumType::kNorthward:
    case EnumType::kNorthEastward:
    case EnumType::kEastward:
    case EnumType::kSouthEastward:
    case EnumType::kSouthward:
    case EnumType::kSouthWestward:
    case EnumType::kWestward:
    case EnumType::kNorthWestward:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::CompassLocationTag val)
{
    using EnumType = Globals::CompassLocationTag;
    switch (val)
    {
    case EnumType::kNorth:
    case EnumType::kNorthEast:
    case EnumType::kEast:
    case EnumType::kSouthEast:
    case EnumType::kSouth:
    case EnumType::kSouthWest:
    case EnumType::kWest:
    case EnumType::kNorthWest:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::DirectionTag val)
{
    using EnumType = Globals::DirectionTag;
    switch (val)
    {
    case EnumType::kUpward:
    case EnumType::kDownward:
    case EnumType::kLeftward:
    case EnumType::kRightward:
    case EnumType::kForward:
    case EnumType::kBackward:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ElectricalDistributionFormFactorTag val)
{
    using EnumType = Globals::ElectricalDistributionFormFactorTag;
    switch (val)
    {
    case EnumType::kMiniature:
    case EnumType::kMoldedCase:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ElectricalDistributionOverVoltageTag val)
{
    using EnumType = Globals::ElectricalDistributionOverVoltageTag;
    switch (val)
    {
    case EnumType::kLineToNeutral:
    case EnumType::kLineToGround:
    case EnumType::kNeutralToGround:
    case EnumType::kLineToLine:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ElectricalMeasurementTag val)
{
    using EnumType = Globals::ElectricalMeasurementTag;
    switch (val)
    {
    case EnumType::kDc:
    case EnumType::kAc:
    case EnumType::kACPhase1:
    case EnumType::kACPhase2:
    case EnumType::kACPhase3:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::HumanActivityTag val)
{
    using EnumType = Globals::HumanActivityTag;
    switch (val)
    {
    case EnumType::kUnknown:
    case EnumType::kPresence:
    case EnumType::kFall:
    case EnumType::kSleep:
    case EnumType::kWalk:
    case EnumType::kWorkout:
    case EnumType::kSit:
    case EnumType::kStand:
    case EnumType::kDance:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::LandmarkTag val)
{
    using EnumType = Globals::LandmarkTag;
    switch (val)
    {
    case EnumType::kAirConditioner:
    case EnumType::kAirPurifier:
    case EnumType::kBackDoor:
    case EnumType::kBarStool:
    case EnumType::kBathMat:
    case EnumType::kBathtub:
    case EnumType::kBed:
    case EnumType::kBookshelf:
    case EnumType::kChair:
    case EnumType::kChristmasTree:
    case EnumType::kCoatRack:
    case EnumType::kCoffeeTable:
    case EnumType::kCookingRange:
    case EnumType::kCouch:
    case EnumType::kCountertop:
    case EnumType::kCradle:
    case EnumType::kCrib:
    case EnumType::kDesk:
    case EnumType::kDiningTable:
    case EnumType::kDishwasher:
    case EnumType::kDoor:
    case EnumType::kDresser:
    case EnumType::kLaundryDryer:
    case EnumType::kFan:
    case EnumType::kFireplace:
    case EnumType::kFreezer:
    case EnumType::kFrontDoor:
    case EnumType::kHighChair:
    case EnumType::kKitchenIsland:
    case EnumType::kLamp:
    case EnumType::kLitterBox:
    case EnumType::kMirror:
    case EnumType::kNightstand:
    case EnumType::kOven:
    case EnumType::kPetBed:
    case EnumType::kPetBowl:
    case EnumType::kPetCrate:
    case EnumType::kRefrigerator:
    case EnumType::kScratchingPost:
    case EnumType::kShoeRack:
    case EnumType::kShower:
    case EnumType::kSideDoor:
    case EnumType::kSink:
    case EnumType::kSofa:
    case EnumType::kStove:
    case EnumType::kTable:
    case EnumType::kToilet:
    case EnumType::kTrashCan:
    case EnumType::kLaundryWasher:
    case EnumType::kWindow:
    case EnumType::kWineCooler:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::LaundryTag val)
{
    using EnumType = Globals::LaundryTag;
    switch (val)
    {
    case EnumType::kNormal:
    case EnumType::kLightDry:
    case EnumType::kExtraDry:
    case EnumType::kNoDry:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::LevelTag val)
{
    using EnumType = Globals::LevelTag;
    switch (val)
    {
    case EnumType::kLow:
    case EnumType::kMedium:
    case EnumType::kHigh:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::LocationTag val)
{
    using EnumType = Globals::LocationTag;
    switch (val)
    {
    case EnumType::kIndoor:
    case EnumType::kOutdoor:
    case EnumType::kInside:
    case EnumType::kOutside:
    case EnumType::kZone:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::MeasurementTypeEnum val)
{
    using EnumType = Globals::MeasurementTypeEnum;
    switch (val)
    {
    case EnumType::kUnspecified:
    case EnumType::kVoltage:
    case EnumType::kActiveCurrent:
    case EnumType::kReactiveCurrent:
    case EnumType::kApparentCurrent:
    case EnumType::kActivePower:
    case EnumType::kReactivePower:
    case EnumType::kApparentPower:
    case EnumType::kRMSVoltage:
    case EnumType::kRMSCurrent:
    case EnumType::kRMSPower:
    case EnumType::kFrequency:
    case EnumType::kPowerFactor:
    case EnumType::kNeutralCurrent:
    case EnumType::kElectricalEnergy:
    case EnumType::kReactiveEnergy:
    case EnumType::kApparentEnergy:
    case EnumType::kSoilMoisture:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::NumberTag val)
{
    using EnumType = Globals::NumberTag;
    switch (val)
    {
    case EnumType::kZero:
    case EnumType::kOne:
    case EnumType::kTwo:
    case EnumType::kThree:
    case EnumType::kFour:
    case EnumType::kFive:
    case EnumType::kSix:
    case EnumType::kSeven:
    case EnumType::kEight:
    case EnumType::kNine:
    case EnumType::kTen:
    case EnumType::kEleven:
    case EnumType::kTwelve:
    case EnumType::kThirteen:
    case EnumType::kFourteen:
    case EnumType::kFifteen:
    case EnumType::kSixteen:
    case EnumType::kSeventeen:
    case EnumType::kEighteen:
    case EnumType::kNineteen:
    case EnumType::kTwenty:
    case EnumType::kTwentyOne:
    case EnumType::kTwentyTwo:
    case EnumType::kTwentyThree:
    case EnumType::kTwentyFour:
    case EnumType::kTwentyFive:
    case EnumType::kTwentySix:
    case EnumType::kTwentySeven:
    case EnumType::kTwentyEight:
    case EnumType::kTwentyNine:
    case EnumType::kThirty:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ObjectIdentificationTag val)
{
    using EnumType = Globals::ObjectIdentificationTag;
    switch (val)
    {
    case EnumType::kUnknown:
    case EnumType::kAdult:
    case EnumType::kChild:
    case EnumType::kRvc:
    case EnumType::kPet:
    case EnumType::kDog:
    case EnumType::kCat:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::PositionTag val)
{
    using EnumType = Globals::PositionTag;
    switch (val)
    {
    case EnumType::kLeft:
    case EnumType::kRight:
    case EnumType::kTop:
    case EnumType::kBottom:
    case EnumType::kMiddle:
    case EnumType::kRow:
    case EnumType::kColumn:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::PowerSourceTag val)
{
    using EnumType = Globals::PowerSourceTag;
    switch (val)
    {
    case EnumType::kUnknown:
    case EnumType::kGrid:
    case EnumType::kSolar:
    case EnumType::kBattery:
    case EnumType::kEv:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::PowerThresholdSourceEnum val)
{
    using EnumType = Globals::PowerThresholdSourceEnum;
    switch (val)
    {
    case EnumType::kContract:
    case EnumType::kRegulator:
    case EnumType::kEquipment:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::RefrigeratorTag val)
{
    using EnumType = Globals::RefrigeratorTag;
    switch (val)
    {
    case EnumType::kRefrigerator:
    case EnumType::kFreezer:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::RelativePositionTag val)
{
    using EnumType = Globals::RelativePositionTag;
    switch (val)
    {
    case EnumType::kUnder:
    case EnumType::kNextTo:
    case EnumType::kAround:
    case EnumType::kOn:
    case EnumType::kAbove:
    case EnumType::kFrontOf:
    case EnumType::kBehind:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::RoomAirConditionerTag val)
{
    using EnumType = Globals::RoomAirConditionerTag;
    switch (val)
    {
    case EnumType::kEvaporator:
    case EnumType::kCondenser:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ServerAttributionContextInformation val)
{
    using EnumType = Globals::ServerAttributionContextInformation;
    switch (val)
    {
    case EnumType::kServerAutomationRule:
    case EnumType::kServerSchedule:
    case EnumType::kServerTimer:
    case EnumType::kSecurity:
    case EnumType::kDemandResponseEventOrSimilarServiceProviderSignalling:
    case EnumType::kPhysicalInteractionOnDevice:
    case EnumType::kInteractionViaAProtocolNotDefinedInThisSpecification:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::SoftwareVersionCertificationStatusEnum val)
{
    using EnumType = Globals::SoftwareVersionCertificationStatusEnum;
    switch (val)
    {
    case EnumType::kDevTest:
    case EnumType::kProvisional:
    case EnumType::kCertified:
    case EnumType::kRevoked:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::StreamUsageEnum val)
{
    using EnumType = Globals::StreamUsageEnum;
    switch (val)
    {
    case EnumType::kInternal:
    case EnumType::kRecording:
    case EnumType::kAnalysis:
    case EnumType::kLiveView:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::SuppliedAttributionContextInformation val)
{
    using EnumType = Globals::SuppliedAttributionContextInformation;
    switch (val)
    {
    case EnumType::kDefaultClientAction:
    case EnumType::kUserInteraction:
    case EnumType::kClientAutomationRule:
    case EnumType::kClientSchedule:
    case EnumType::kClientTimer:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::SwitchesTag val)
{
    using EnumType = Globals::SwitchesTag;
    switch (val)
    {
    case EnumType::kOn:
    case EnumType::kOff:
    case EnumType::kToggle:
    case EnumType::kUp:
    case EnumType::kDown:
    case EnumType::kNext:
    case EnumType::kPrevious:
    case EnumType::kEnterOkSelect:
    case EnumType::kCustom:
    case EnumType::kOpen:
    case EnumType::kClose:
    case EnumType::kStop:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::TariffPriceTypeEnum val)
{
    using EnumType = Globals::TariffPriceTypeEnum;
    switch (val)
    {
    case EnumType::kStandard:
    case EnumType::kCritical:
    case EnumType::kVirtual:
    case EnumType::kIncentive:
    case EnumType::kIncentiveSignal:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::TariffUnitEnum val)
{
    using EnumType = Globals::TariffUnitEnum;
    switch (val)
    {
    case EnumType::kKWh:
    case EnumType::kKVAh:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::TestGlobalEnum val)
{
    using EnumType = Globals::TestGlobalEnum;
    switch (val)
    {
    case EnumType::kSomeValue:
    case EnumType::kSomeOtherValue:
    case EnumType::kFinalValue:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::ThreeLevelAutoEnum val)
{
    using EnumType = Globals::ThreeLevelAutoEnum;
    switch (val)
    {
    case EnumType::kAuto:
    case EnumType::kLow:
    case EnumType::kMedium:
    case EnumType::kHigh:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
static auto __attribute__((unused)) EnsureKnownEnumValue(Globals::WebRTCEndReasonEnum val)
{
    using EnumType = Globals::WebRTCEndReasonEnum;
    switch (val)
    {
    case EnumType::kICEFailed:
    case EnumType::kICETimeout:
    case EnumType::kUserHangup:
    case EnumType::kUserBusy:
    case EnumType::kReplaced:
    case EnumType::kNoUserMedia:
    case EnumType::kInviteTimeout:
    case EnumType::kAnsweredElsewhere:
    case EnumType::kOutOfResources:
    case EnumType::kMediaTimeout:
    case EnumType::kLowPower:
    case EnumType::kPrivacyMode:
    case EnumType::kUnknownReason:
        return val;
    default:
        return EnumType::kUnknownEnumValue;
    }
}
} // namespace Clusters
} // namespace app
} // namespace chip
